### ISSUE TITLE
Persistent ParticipantStore

### ISSUE THREAD

**Issue by marcgs** [eclipse-dataspaceconnector/RegistrationService#33]
# Feature Request

Support for persistent ParticipantStore

## Which Areas Would Be Affected?
Registration Service

## Why Is the Feature Desired?
Currently the Registration Service only supports an in memory version of `ParticipantStore`. As a consequence, whenever it is restarted, all stored Participants are lost.

## Solution Proposal
As done for most stores in https://github.com/eclipse-dataspaceconnector/DataSpaceConnector, two extensions will be provided:

- one for SQL databases,
- one for CosmosDB.

## Type of Issue
New feature

## Checklist

- [ ] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by bscholtes1A** [comment]
@wolf4ood @jimmarino  can we close this one ? 
as both SQL and Cosmos implementations have now been completed.

**Comment by bscholtes1A** [comment]
Closing the issue as both PostgreSQL and CosmosDB stores have been implemented.
